apiVersion: v1
kind: Service
metadata:
  name: bridge-service
  namespace: dev5
spec:
  selector:
    app: bridge-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
